name: First Workflow
on:[push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello, World!"
            - name:Multiline commands
              run: |
                echo "This is line 1"
                echo "This is line 2"
                echo "This is line 3"
                node -v
                npm -v
                